// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcoZ7oQhTS3iY_MepvI-sjl8atnZVCuA',
    appId: '1:697754198064:web:60793b8ee24d1a7f720df5',
    messagingSenderId: '697754198064',
    projectId: 'gojo--app',
    authDomain: 'gojo--app.firebaseapp.com',
    storageBucket: 'gojo--app.appspot.com',
    measurementId: 'G-1CSRF81QCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40WZVjGtZ2dfYZn1W7PH2ztNS3cQhM3I',
    appId: '1:697754198064:android:d8f061a43d4c97ef720df5',
    messagingSenderId: '697754198064',
    projectId: 'gojo--app',
    storageBucket: 'gojo--app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2L1eugCO4d-VZqWNVz9MsXVEb17g2zVQ',
    appId: '1:697754198064:ios:b4d0ebe1a3167228720df5',
    messagingSenderId: '697754198064',
    projectId: 'gojo--app',
    storageBucket: 'gojo--app.appspot.com',
    iosBundleId: 'com.example.gojoapp',
  );
}
